#! /bin/bash
if [[ "$#" -eq 1 ]];
 then
 if [ $1 == --version ]; 
  then
   echo "v.0.1.0"
 elif [ $1 == --help ];
  then
   echo "help infomation of the internctl"
 fi  
elif [[ "$#" -eq 2 ]];
 then	
 if [ $1 == cpu ] && [ $2 == getinfo ];
  then
   lscpu
 elif [ $1 == memory ] && [ $2 == getinfo ];
  then
   free
 elif [ $1 == user ] && [ $2 == list ];
  then
   cat /etc/passwd
 fi
elif [[ "$#" -eq 3 ]];
 then	
 if [ $1 == user ] && [ $2 == create ];
  then
   useradd $3
 elif [ $1 == user ] && [ $2 == list ] && [ $3 == --sudo-only ];
  then
   getent group root
 elif [ $1 == file ] && [ $2 == getinfo ];
  then
   ls -l $3	  
 fi
elif [[ "$#" -eq 4 ]];
 then
 if [ $1 == file ] && [ $2 == getinfo ] && [ $3 == --size ] || [ $3 == -s ];
  then
   wc -c $4
 elif [ $1 == file ] && [ $2 == getinfo ] && [ $3 == --permissions ] || [ $3 == -p ];
  then
   ls -l $4 |awk '{ print $1; }'
 elif [ $1 == file ] && [ $2 == getinfo ] && [ $3 == --owner ] || [ $3 == o ];
  then
   stat -c '%U' $4
 elif [ $1 == file ] && [ $2 == getinfo ] && [ $3 == --last-modified ] || [ $3 == m ];
  then
   stat -c '%y' $4
 fi
fi
