#! /bin/bash
if [[ "$#" -eq 1 ]];
 then
 if [ $1 == --version ]; 
  then
   echo "v.0.1.0"
 elif [ $1 == --help ];
  then
   echo "help infomation of the internctlinternsctl
NAME
internsctl : vreate some specific operations
SYNOPSIS
   internsctl [options]... file..
Description:
Version: v0.1.0
basically this command do some basic types of operation like lscpu , useradd and
 etc
some parameter of this command are given below
--size,-s ->gives size of file
--permissions,-p -> gives permisiion associated with a file
--owner,-o -> tells owner of file
--last-modified,-m -> gives last modify date

AUTHOR
  WRITTEN BY VIJAY YADAV
  
 REPORTING BUGS
    connect with vijay on linkdin
   
  COPYRIGHT
    COPYRIGHT@2246
  SEE ALSO
   "
 else
   echo "Command Not Found"
 fi  
elif [[ "$#" -eq 2 ]];
 then	
 if [ $1 == cpu ] && [ $2 == getinfo ];
  then
   lscpu
 elif [ $1 == memory ] && [ $2 == getinfo ];
  then
   free
 elif [ $1 == user ] && [ $2 == list ];
  then
   cat /etc/passwd
 else
   echo "Command Not Found"
 fi
elif [[ "$#" -eq 3 ]];
 then	
 if [ $1 == user ] && [ $2 == create ];
  then
   useradd $3
 elif [ $1 == user ] && [ $2 == list ] && [ $3 == --sudo-only ];
  then
   getent group root
 elif [ $1 == file ] && [ $2 == getinfo ];
  then
   echo "File:       $3"
   echo "Access:     `ls-l $3 |awk '{ print $1; }'`"
   echo "Size(B):    `stat -c '%U' $3`"
   echo "Owner:      `stat -c '%y' $3`"
 else
  echo "Command Not Found"
 fi
elif [[ "$#" -eq 4 ]];
 then
 if [ $1 == file ] && [ $2 == getinfo ] && [ $3 == --size ] || [ $3 == -s ];
  then
   wc -c $4
 elif [ $1 == file ] && [ $2 == getinfo ] && [ $3 == --permissions ] || [ $3 == -p ];
  then
   ls -l $4 |awk '{ print $1; }'
 elif [ $1 == file ] && [ $2 == getinfo ] && [ $3 == --owner ] || [ $3 == o ];
  then
   stat -c '%U' $4
 elif [ $1 == file ] && [ $2 == getinfo ] && [ $3 == --last-modified ] || [ $3 == m ];
  then
   stat -c '%y' $4
 else
   echo "Command Not Found"
 fi
else
  echo "Command Not Found"
fi
